### ISSUE TITLE
Comminssioner screen isn't really clear

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/particle-android#55]
As discussed in this [thread](https://community.particle.io/t/xenon-cannot-connect-to-mesh/46452), users don't quite get the meaning of the commissioner setup and admittedly the text doesn't really tell the story well - also instead of mentioning Xenon as commissioner a more generic term would be good, especially if you only have the gateway (Argon/Boron) as assisting device.

![image](https://user-images.githubusercontent.com/6604878/50315313-8dba5700-04b2-11e9-8181-d19942a14ed1.png)

This screen talks about "adding Xeonon to network" then mentinones "this device" (naturally users would apply this to the Xenon they are about to add and not a *second* Xenon)  which should act as commissioner which should help itself to connect - I can see how that is confusing for someone who does only knows what the app says and doesn't already know the background of the commissioning process.

**Comment by ScruffR** [comment]
Even after the update where the commissioner screen only shows the video, the next screen *insists* in using a Xenon as commissioner - **it isn't necessarily a Xenon**, so rather use *"device"* or *"Xenon/Argon/Boron"*

**Comment by marc-gist** [comment]
I had issues here. hopefully you will consider updating this screen, adding more to the animation to show that it can be the gateway device which needs to be put in "blue flashing" mode and scanned.  took me 20min or so to figure out :(

**Comment by gusgonnet** [comment]
I was trying to re-add a Xenon to a network where I had only one Xenon (the one I was trying to re-add) and the gateway (an Argon) and this blocked me for a whole afternoon. So when the app said: scan the other Xenon I was out of luck since I did not have another Xenon...

If it could be changed to another device in the network that would be helpful.
Thanks!

**Comment by jensck** [comment]
This is fixed.
