### ISSUE TITLE
Bintray links to 'old' spark version of cloud sdk

### ISSUE THREAD

**Issue by markoImake** [particle-iot/particle-android#80]
The bintray cloud-sdk package links to the old archived spark repo (https://github.com/particle-iot/spark-sdk-android). 
This applies to all of the following:
compile 'io.particle:cloudsdk:0.5.1
https://dl.bintray.com/particle/android/io/particle/cloudsdk/0.5.1/
https://bintray.com/particle/android/cloud-sdk/

**Comment by jensck** [comment]
I've fixed this on the bintray website, and the gradle file will be updated shortly with the current. The binary packages themselves will reflect this next time we publish a new version.

Thanks for the heads up!
