### ISSUE TITLE
cloud sdk login no longer works

### ISSUE THREAD

**Issue by GonzRon** [particle-iot/particle-android#81]
I m trying to generate a new access token by calling the deviceSetup 0.6.3 loginActivity

My username and password work correctly, using postman i can send a request to https://api.particle.io/oauth/token with a grant_type of password, and my username and password in the body
![2019-09-12_18-55-52](https://user-images.githubusercontent.com/18006895/64826608-3489da80-d58f-11e9-8ee7-7f752366c099.jpg)

So I set some breakpoints to figure out why I was getting this exception:
```

E/Async: Error calling API: User credentials are invalid
    io.particle.android.sdk.cloud.exceptions.ParticleLoginException: retrofit.RetrofitError: 400 
        at io.particle.android.sdk.cloud.ParticleCloud.logIn(ParticleCloud.java:177)
        at io.particle.android.sdk.accountsetup.LoginActivity$1.callApi(LoginActivity.java:173)
        at io.particle.android.sdk.accountsetup.LoginActivity$1.callApi(LoginActivity.java:170)
        at io.particle.android.sdk.utils.Async$AsyncApiWorker.doInBackground(Async.java:111)
        at io.particle.android.sdk.utils.Async$AsyncApiWorker.doInBackground(Async.java:79)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: retrofit.RetrofitError: 400 
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy1.logIn(Unknown Source)
        at io.particle.android.sdk.cloud.ParticleCloud.logIn(ParticleCloud.java:174)
        at io.particle.android.sdk.accountsetup.LoginActivity$1.callApi(LoginActivity.java:173) 
        at io.particle.android.sdk.accountsetup.LoginActivity$1.callApi(LoginActivity.java:170) 
        at io.particle.android.sdk.utils.Async$AsyncApiWorker.doInBackground(Async.java:111) 
        at io.particle.android.sdk.utils.Async$AsyncApiWorker.doInBackground(Async.java:79) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

I traced it all the way to the retrofit rest adapter and discovered it was sending the username in the body with an encoded @ symbol -> %40
![2019-09-12_18-35-04](https://user-images.githubusercontent.com/18006895/64826553-0efcd100-d58f-11e9-84c2-7fda08d532ad.jpg)

I noticed also in the screencap that the body is of Type FormUrlEncoded, and perhaps this should be "application/json;charset=UTF-8" 

So here's what happens if I encoded the @ symbol in postman, same result:
![2019-09-12_18-52-36](https://user-images.githubusercontent.com/18006895/64826552-0efcd100-d58f-11e9-9c89-0544a099feea.jpg)

**Comment by jensck** [comment]
I'll take a look and see if I can reproduce these findings.

**Comment by jensck** [comment]
I understand why you'd suspect the form encoding is a bug, but it's intentional.

As for the difference you're seeing between the debugger and Postman, Postman is probably hiding some information from you here.  You've selected `x-www-form-urlencoded` in your screenshot, but Postman doesn't expect you to enter your parameters pre-encoded; it's doing the encoding for you. 
 Try setting up that same request again and hit the `Code` button, which we'll show you the raw request data -- you'll find that the `@` has been URL-encoded as %40 just like what the Cloud SDK is doing.

Anyway, it appears that the Cloud SDK is doing what it should be (it's working fine for the Tinker app and all the other users of the lib).  Have you tried triple-checking that your username & password are correct when you're logging in through the app?

Since I'm unable to repro and everything appears to be working as intended, I'm going to close this.  If you've reproduced the problem after making certain that it's not a typo (etc), feel free to reopen this issue.

**Comment by GonzRon** [comment]
I double and triple checked the password in the debugger.  I agree it's probably not an encoding issue, there must be something else going on.

**Comment by GonzRon** [comment]
OK I figured out the problem, in my postman request, I'm using the base64 encoded representation of "particle:particle" in my Authorization: Basic Header.

In the android application, I see the base64 encoded value of my oauth client id and client secret.

Apparently using particle:particle works, but not the oauthclient:secret
My app was written a year or two ago, so this has always worked until a some months ago but I didn't bother addressing it until now.  I don't know if that's something I can control, perhaps this is related to some of the new changes on the particle cloud platform?

Please advise @jensck any suggestions would be welcome.

**Comment by GonzRon** [comment]
@jensck perhaps I am being a bit hasty in expecting a response, but can you a. address my latest comment, b. reopen this ticket, or c. express a preference for me to open a new ticket with the above latest information?

**Comment by jensck** [comment]
This looks like legit enough evidence to reopen. Thanks for the detailed update.

I'll try to look into this before the weekend.

**Comment by jensck** [comment]
Apologies I couldn't get to this yet; I should be able to look at it Monday.

In the meantime, can you try setting up a new project using newly-generated Oauth credentials and see if that sample exhibits the same problem?

**Comment by GonzRon** [comment]
> Apologies I couldn't get to this yet; I should be able to look at it Monday.

any luck?

**Comment by GonzRon** [comment]
so are we going to be able to get any attention on this ticket from Particle @idokleinman ?

**Comment by jensck** [comment]
Sorry about the delay.  I tested the flow I gave above (setting up a new project using newly-generated Oauth credentials) and that worked as expected.

Try cloning [this repo](https://github.com/jensck/particle-android-auth-test) and putting in your values for `oauth_client_id` and `oauth_client_secret`, and checking the logcat output.

**Comment by GonzRon** [comment]
really appreciate the effort Jens.

Here was my original reply (which is no longer valid, well technically, only partly valid.)

> Thanks for the effort jensck, based on your test, I'm going to go ahead and assume that if I test creating new Oauth Client creds in the auth portion of the site (under the product) this will all start working again and it has absolutely nothing to do with the Particle Android SDK.  I'll go ahead and test this anyways, but instead, I'm guessing this likely has to do with some of the changes made on the cloud platform.  Meaning that something changed on the cloud side that's preventing my currently configured Oauth Client ID or password from working. If that's the case, how should I go about tracking down why my client doesn't work?


So I cloned the repo compiled and ran in debug.  Would you believe it? It also didn't work with my creds.
```
D/Retrofit: ---> HTTP POST https://api.particle.io/oauth/token
    Authorization: Basic (valid base64 encoded string redacted from output)
    Content-Type: application/x-www-form-urlencoded; charset=UTF-8
D/Retrofit: Content-Length: 75
D/Retrofit: grant_type=password&username=redacted%40redacted.com&password=redacted
D/Retrofit: ---> END HTTP (75-byte body)
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/TcpOptimizer: TcpOptimizer-ON
W/articleauthtes: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (light greylist, reflection)
W/articleauthtes: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (light greylist, reflection)
D/Retrofit: <--- HTTP 400 https://api.particle.io/oauth/token (959ms)
    date: Wed, 02 Oct 2019 00:41:08 GMT
    content-type: application/json; charset=utf-8
    content-length: 76
    server: nginx/1.15.10
    x-request-id: 9a5bb1d0027bf0ccfb5aed2b2480cea2
    access-control-allow-origin: *
    cache-control: no-store
    pragma: no-cache
    OkHttp-Sent-Millis: 1569976868233
D/Retrofit: OkHttp-Received-Millis: 1569976868537
D/Retrofit: {"error":"invalid_grant","error_description":"User credentials are invalid"}
D/Retrofit: <--- END HTTP (76-byte body)
E/AUTHTEST: Error logging in user
    io.particle.android.sdk.cloud.exceptions.ParticleLoginException: retrofit.RetrofitError: 400 
        at io.particle.android.sdk.cloud.ParticleCloud.logIn(ParticleCloud.java:177)
        at io.particle.particleauthtest.MainActivity$logIn$1.invokeSuspend(MainActivity.kt:57)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
     Caused by: retrofit.RetrofitError: 400 
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy1.logIn(Unknown Source)
        at io.particle.android.sdk.cloud.ParticleCloud.logIn(ParticleCloud.java:174)
        at io.particle.particleauthtest.MainActivity$logIn$1.invokeSuspend(MainActivity.kt:57) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740) 
```

But that's not all. I created a new Oauth Client under my PRODUCT in the cloud console (console.particle.io/productName/authentication), as based on your last comment, I was certain that this was related to back end changes on the particle cloud platform that either broke my existing client or screwed something else up.  So I used the new Oauth Creds, they don't work either with your test app.

So then I went ahead and just created Oauth Client Creds under the root section of the console, in other words, not the auth tab under a product, just the basic auth tab under my user account, i.e.
https://console.particle.io/authentication VS console.particle.io/productName/authentication

The oauth client I created under the root authentication tab for the account works.  Oauth Clients that I create under the authentication section of any product do not work.

So 
does not work: clients created in: console.particle.io/productName/authentication
works:  Oauth clients created in:  console.particle.io/authentication 

So this is not technically a problem with the SDK, I am terribly sorry to have bothered you.  What would you suggest is my best recourse at this point having discovered this tidbit?

**Comment by GonzRon** [comment]
OK, I get it, only customers created under the product that contains the Oauth Client can login to the app with the oauth client creds.  I am guessing that this has always worked incorrectly, i.e. you could use a non product username / password with a product specific oauth client, and this little "feature was fixed".

Sorry for bothering you @jensck

**Comment by jensck** [comment]
@GonzRon no worries. I appreciated the detailed report, even though it wasn't an SDK problem in the end. Glad to see you got it figured out! :)

**Comment by GonzRon** [comment]
I went ahead and used the console to unclaim the device, then used postman to claim the device for my customer account, that was a bit tricky, but once I got all the creds and oauth clients lined up, I was able to claim the device for my customer, and the app started working again but I had to make sure to login as the customer.  So this used to work the wrong way, and now you guys fixed it, security tends towards always getting tighter, and that's a good thing.  🍻

**Comment by izmevid** [comment]
Hi,

I am right now experiencing the same issue and I think that the root cause is the same: I have a Photon which I changed from one account to another and I am now using it with the new account. 

With Android Studio I get this "io.particle.android.sdk.cloud.exceptions.ParticleCloudException: retrofit.RetrofitError" Error.

Could you please tell me how exactly you fixed that? 

Thanks!
David

**Comment by GonzRon** [comment]
Hi @izmevid 
>With Android Studio I get this "io.particle.android.sdk.cloud.exceptions.ParticleCloudException: retrofit.RetrofitError" Error.
is a generic error.  The real error should be further in the stack. if you notice above I received:

>    io.particle.android.sdk.cloud.exceptions.ParticleLoginException: retrofit.RetrofitError: 400 
notice the 400 error code in my message, you should paste your entire stack exception. I recommend opening a new ticket and providing a detailed description and referencing this issue so that someone from particle (or anyone) can try to help.

You may think that the issue is related to this ticket, but you didn't detail why you think that is the case.  In my case, I detailed my steps generally.  You will need to unclaim your device using the correct bearer token and client and reclaim the device with the account that you are wanting to move the device to.  

Hope that helps: 🍻
