### ISSUE TITLE
Trouble compiling examples 'quickstartFile' does not exist.

### ISSUE THREAD

**Issue by jacky4566** [particle-iot/particle-android#82]
I am having some trouble compiling the sdk example. 
This is a fresh install of Android Studio with SDK 28

What is my next step to resolve?

```
* What went wrong:
A problem was found with the configuration of task ':app:processDebugGoogleServices'.
> File 'S:\...\particle-android-master\app\google-services.json' specified for property 'quickstartFile' does not exist.
```

**Comment by bloukingfisher** [comment]
If you've not created and added your own google-services.json file from https://firebase.google.com/, then in the app/build.gradle comment out:
apply plugin: 'io.fabric' (line 22)
apply plugin: 'com.google.gms.google-services' (line 147)

In settings.gradle comment out:
sdk_example_app
setup_testapp
setup_exampleapp

That's assuming you're running the "app". Give that a try. Otherwise adjust accordingly in settings.grade

**Comment by jacky4566** [comment]
OH. Ok.
I created a firebase account and added the appropriate JSON. That seems to have fixed the issue.
Now I'm running into issues with io.particle.firmwareprotos.ctrl.Common.IPAddressOrBuilder which i think you are [already working on?](githubhttps://community.particle.io/t/tinker-app-source-code-for-android/50952/11)

**Comment by bloukingfisher** [comment]
The way I solved it is:
uncomment lines 39-46 where v4 and v6 is used in \mesh\src\main\java\io\particle\mesh\setup\flow\setupsteps\StepEnsureEthernetHasIpAddress.kt

        val iface = reply.`interface`
        for (addyList in listOf(iface.ipv4Config.addressesList, iface.ipv6Config.addressesList)) {

          /*  val address = addyList.firstOrNull {
                it.address.v4.address.truthy() || it.address.v6.address.truthy()

            }
            if (address != null) {
                log.debug { "IP address on ethernet (interface ${ethernet.index}) found: $address" }
                return
            }*/
        }

**Comment by jacky4566** [comment]
Great, that at least gets me the example working.

**Comment by jensck** [comment]
Update: the firmwareprotos compilation issue is finally fixed in `master`.
