### ISSUE TITLE
Particle.variable(INT) > 9999999 don't fit into view

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/particle-android#84]
While 9999999 can be displayed 10000000 cannot but only the first digit would be shown.
If you had 23456789 you would get 2 in the app.

Tested on Photon 1.4.2 - App version I _guess_ v3.02 (not found in app - what about an About box in the ... menu?) 
```
int32_t  sigInt; 

void setup() {
  Particle.function("set", setValues);
  Particle.variable("int", sigInt);  
}

int setValues(const char* arg) {
  sigInt = strtol(arg, NULL, 0);
  return sigInt;
}
```

Console shows the correct value as expected.

**Comment by bloukingfisher** [comment]
FYI, @ScruffR if you sign out of the app, close it and then get back to the welcome screen the version number should be displayed in the bottom...scratch that. That seems to still work for iOS but not Android.
In Android, long press on the app icon >App info > scroll to bottom for version.

You should maybe add what device you are using. I find more things chopped off on a test iPhone 5 that larger screens but just displaying the first digit is another story. 

If you press on the variable to copy it to the clipboard, does it then show the full number?

**Comment by ScruffR** [comment]
> You should maybe add what device you are using. 

Samsung Galaxy A3 (2017)

When I long-tap the App icon I only get [ Select Items | Add to Start screen | Uninstall ] 😕

**Comment by jensck** [comment]
@ScruffR can I get a screenshot of what you're seeing?  Thanks!

**Comment by ScruffR** [comment]
This is what I see in console
![image](https://user-images.githubusercontent.com/6604878/67273927-ba1e7580-f4bf-11e9-8a56-c42f439de2fd.png)
And this in the Android App (tested on multiple devices: Android Galaxy A3 (2017), Huawai Mate8, Android Galaxy Tab S3)
![image](https://user-images.githubusercontent.com/6604878/67274083-0cf82d00-f4c0-11e9-92d6-f9aea69db0e4.png)

**Comment by jensck** [comment]
Thanks for the screenshots -- I'll get this fixed for the next app release.

**Comment by jensck** [comment]
Thanks for the extra info, @ScruffR . I'll include a fix in the next app update.

**Comment by jensck** [comment]
This is fixed now.  An app update with this fix applied will be available within a day or so.
