### ISSUE TITLE
Unable to change value for indicator_light_setup_color_name

### ISSUE THREAD

**Issue by jeremiahogutu** [particle-iot/particle-android#90]
I am unable to change the values for **indicator_light_setup_color_name** and **setup_button_identifier**. I am integrating the android sdk into a react native app. I am able to customize most of the values in the android sdk by adding them to string.xml, but for some reason it does not work for the values mentioned above.

**Comment by jensck** [comment]
`indicator_light_setup_color_name` and `setup_button_identifier` are just an internal-use strings for templating; I'm guessing you were reading the source? :)

The values you want are `listen_mode_led_color_name` and `mode_button_name`, respectively.  For future ref, all of these [customizations are documented here](https://docs.particle.io/reference/SDKs/android/#customization)!

**Comment by jeremiahogutu** [comment]
That worked perfect. Thank you!
